name: build-proxypool

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/proxypool-build.yml'

jobs:

  build-proxypool:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          repository: callacat/proxypool

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Go mod download
        run: |
          go mod download

      - name: Make docker
        run: |
          make docker
          mv ./bin/proxypool-docker proxypool

      - name: 上传
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: proxypool